[2024-12-22T19:40:57.925119-03:00] error_logger.ERROR: htmlspecialchars(): Argument #1 ($string) must be of type string, array given {"exception":"[object] (TypeError(code: 0): htmlspecialchars(): Argument #1 ($string) must be of type string, array given at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\controllers\\user\\Matricula\\MatriculaController.php:32)"} []
[2024-12-22T19:40:57.926471-03:00] error_logger.ERROR: TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 32 Stack trace:   1. TypeError->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   2. htmlspecialchars() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   3. cefet\SyncLab\controllers\user\Matricula\MatriculaController->SelecionarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   4. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40   6. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   7. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:42:21.974534-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:42:21.976636-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:42:22.851933-03:00] error_logger.ERROR: Undefined array key "idMat" {"exception":"[object] (Whoops\\Exception\\ErrorException(code: 2): Undefined array key \"idMat\" at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\controllers\\user\\Matricula\\MatriculaController.php:32)"} []
[2024-12-22T19:42:22.853394-03:00] error_logger.ERROR: Whoops\Exception\ErrorException: Undefined array key "idMat" in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 32 Stack trace:   1. Whoops\Exception\ErrorException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   2. Whoops\Run->handleError() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   3. cefet\SyncLab\controllers\user\Matricula\MatriculaController->SelecionarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   4. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40   6. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   7. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:43:18.833712-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:43:18.835133-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:43:19.741801-03:00] error_logger.ERROR: htmlspecialchars(): Argument #1 ($string) must be of type string, array given {"exception":"[object] (TypeError(code: 0): htmlspecialchars(): Argument #1 ($string) must be of type string, array given at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\controllers\\user\\Matricula\\MatriculaController.php:32)"} []
[2024-12-22T19:43:19.743144-03:00] error_logger.ERROR: TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 32 Stack trace:   1. TypeError->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   2. htmlspecialchars() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   3. cefet\SyncLab\controllers\user\Matricula\MatriculaController->SelecionarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   4. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40   6. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   7. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:45:25.634482-03:00] error_logger.ERROR: trim(): Argument #1 ($string) must be of type string, array given {"exception":"[object] (TypeError(code: 0): trim(): Argument #1 ($string) must be of type string, array given at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\controllers\\user\\Matricula\\MatriculaController.php:32)"} []
[2024-12-22T19:45:25.636063-03:00] error_logger.ERROR: TypeError: trim(): Argument #1 ($string) must be of type string, array given in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 32 Stack trace:   1. TypeError->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   2. trim() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   3. cefet\SyncLab\controllers\user\Matricula\MatriculaController->SelecionarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   4. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40   6. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   7. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:45:46.667718-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:45:46.668981-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:45:47.446280-03:00] error_logger.ERROR: Undefined array key 0 {"exception":"[object] (Whoops\\Exception\\ErrorException(code: 2): Undefined array key 0 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\controllers\\user\\Matricula\\MatriculaController.php:32)"} []
[2024-12-22T19:45:47.447876-03:00] error_logger.ERROR: Whoops\Exception\ErrorException: Undefined array key 0 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 32 Stack trace:   1. Whoops\Exception\ErrorException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   2. Whoops\Run->handleError() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:32   3. cefet\SyncLab\controllers\user\Matricula\MatriculaController->SelecionarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   4. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40   6. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:40}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   7. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:46:42.432714-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:46:42.434316-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:46:50.356220-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:46:50.357411-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:46:51.083919-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:46:51.085103-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:01.768616-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:01.770037-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:03.158851-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:03.160230-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:06.187709-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:06.188891-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:07.839419-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:07.840661-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:08.768992-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:08.770241-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:14.312723-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:14.313884-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:20.519394-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:20.520621-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:23.130969-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:23.132133-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:47:24.091751-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:47:24.092938-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:48:33.117614-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:48:33.119044-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:48:33.846836-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:48:33.848141-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:49:37.022058-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:49:37.023320-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:49:40.389190-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:49:40.390406-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:11.939863-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:11.941145-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:12.707203-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:12.708886-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:12.905808-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:12.906956-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:14.531685-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:14.532912-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:15.636251-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:15.637525-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:21.496870-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:21.498639-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:50:22.648608-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:50:22.649817-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:54:37.497325-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:54:37.498892-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:54:41.532474-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:54:41.533666-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:54:43.872757-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:54:43.873965-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:54:44.480974-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:54:44.482125-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:54:45.294975-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:54:45.296238-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:56:53.358215-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:56:53.359743-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:56:57.485324-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:56:57.486559-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:56:58.970375-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:56:58.971549-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:08.828226-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:57:08.829388-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:14.716674-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:57:14.717839-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:19.625096-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:57:19.626300-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:28.166139-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:57:28.167362-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:28.999750-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:57:29.001338-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:36.514226-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:57:36.515374-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:45.166284-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:57:45.167467-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:57:48.245452-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:57:48.246593-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:58:00.199441-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:58:00.200708-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:58:01.490857-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:58:01.492081-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:58:07.225742-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:58:07.227022-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:59:48.676450-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:59:48.678530-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:59:53.827780-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T19:59:53.829098-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T19:59:58.748622-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T19:59:58.749802-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:02.788914-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T20:00:02.790201-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:04.804312-03:00] error_logger.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 {"exception":"[object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:85)"} []
[2024-12-22T20:00:04.806301-03:00] error_logger.ERROR: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'matriculaMat' at row 1 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 85 Stack trace:   1. PDOException->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   2. PDOStatement->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:85   3. cefet\SyncLab\classes\User->requisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\RequisitarController.php:37   4. cefet\SyncLab\controllers\user\Matricula\RequisitarController->RequisitarMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   6. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41   7. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:41}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   8. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:06.795333-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:06.796638-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:22.464566-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:22.465902-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:25.726824-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:25.728114-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:31.942687-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:31.943853-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:32.599427-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:32.600563-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:33.607929-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:33.609126-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:34.043315-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:34.044559-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:34.486836-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:34.488064-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:34.941722-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:34.942877-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:00:41.115940-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:00:41.117150-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:12:59.683801-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:12:59.685465-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:13:01.557409-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:13:01.558639-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:13:05.958799-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:13:05.960024-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:13:08.229589-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:13:08.230759-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:13:09.927084-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:13:09.928248-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2024-12-22T20:20:25.176527-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2024-12-22T20:20:25.178055-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:57:39.142058-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:57:39.203629-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:57:48.937814-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:57:48.939041-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:21.267620-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:21.268796-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:29.016413-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:29.017596-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:34.414831-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:34.415995-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:39.956956-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:39.958140-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:44.276757-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:44.277902-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:48.943554-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:48.944702-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:53.510544-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:53.511690-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T12:58:55.992253-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T12:58:55.993708-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:01:19.169205-03:00] error_logger.ERROR: cefet\SyncLab\classes\User::carregarMatriculasAtivas(): Argument #1 ($idUsuario) must be of type int, null given, called in C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 22 {"exception":"[object] (TypeError(code: 0): cefet\\SyncLab\\classes\\User::carregarMatriculasAtivas(): Argument #1 ($idUsuario) must be of type int, null given, called in C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\controllers\\user\\Matricula\\MatriculaController.php on line 22 at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\classes\\User.php:125)"} []
[2025-01-04T13:01:19.170634-03:00] error_logger.ERROR: TypeError: cefet\SyncLab\classes\User::carregarMatriculasAtivas(): Argument #1 ($idUsuario) must be of type int, null given, called in C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php on line 22 in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php on line 125 Stack trace:   1. TypeError->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\classes\User.php:125   2. cefet\SyncLab\classes\User->carregarMatriculasAtivas() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\controllers\user\Matricula\MatriculaController.php:22   3. cefet\SyncLab\controllers\user\Matricula\MatriculaController->viewMatricula() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   4. call_user_func() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:38   5. cefet\SyncLab\router\Router->load() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:11   6. cefet\SyncLab\router\Router->{closure:C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\routes.php:11}() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:105   7. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:01:19.200028-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:01:19.201338-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:02:59.712895-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:02:59.714124-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:03:17.245990-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:03:17.247199-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:03:24.314627-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:03:24.316673-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:03:27.543235-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:03:27.544520-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:03:29.190211-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:03:29.191393-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:03:29.816799-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:03:29.817992-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
[2025-01-04T13:03:30.408278-03:00] error_logger.ERROR: A rota não existe (/favicon.ico) {"exception":"[object] (Exception(code: 0): A rota não existe (/favicon.ico) at C:\\Users\\Victor\\Documents\\SyncLAbDWEBII\\SyncLabDWEBII\\app\\router\\Router.php:92)"} []
[2025-01-04T13:03:30.409478-03:00] error_logger.ERROR: Exception: A rota não existe (/favicon.ico) in file C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php on line 92 Stack trace:   1. Exception->() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\app\router\Router.php:92   2. cefet\SyncLab\router\Router->execute() C:\Users\Victor\Documents\SyncLAbDWEBII\SyncLabDWEBII\index.php:10  [] []
